# Copyright (c) 2011 Solano Labs All Rights Reserved

development:
  api:
    scheme: http
    host: tddium.lvh.me
    port: 3000
    version: 1

production:
  api:
    scheme: https
    host: api.tddium.com
    version: 1

staging:
  api:
    scheme: https
    host: stage-api.tddium.com
    version: 1

test:
  api:
    scheme: http
    host: tddium.lvh.me
    port: 3000
    version: 1

mimic:
  api:
    scheme: http
    host: localhost
    port: 8080
    version: 1
